export const ROUTING = {
  HOME: 'home',
  PROFILE: 'profile',
  MY_COURSE: 'profile/courses',
  LOGIN: 'login',
  REGISTER: 'register',
  BOTTOM_TAB: 'BottomTab',
  SIGN_UP: 'sign-up',
  ONBOARDING: 'on-boarding',
  RESET_PASSWORD: 'reset-password',
  SETTING: 'setting',
  LESSION_DETAIL: 'lession-detail',
  NOTIFICATION: 'notification',
  INBOX: 'inbox',
  DETAIL: 'detail',
  TRANSACTION_COMPLETED: 'transaction-completed',
};
